solved given issues
ksakash/newton-school-lessons pull request #64
Opened 2023-11-18 22:02 UTC by mk0904

2023-11-19 03:46 UTC, ksakash requested changes

2023-11-19 03:46 UTC, ksakash commented on README.md
> +    ```basg
It will be bash here.

2023-11-19 03:57 UTC, ksakash commented
@mk0904 can you comment which all issues did you solve? so that i could close them.

2023-11-20 09:12 UTC, mk0904 commented
> @mk0904 can you comment which all issues did you solve? so that i could close them.

Sir i solved each one of them i guess. So almost every issue created.

2023-11-20 14:52 UTC, merged